<?php
define('STATUS_CODE_UNAUTHORIZED', 401);
define('STATUS_CODE_NOT_FOUND', 404);
define('STATUS_CODE_SUCCESS', 200);
define('STATUS_CODE_UNPROCESSABLE_ENTITY', 422);
define('STATUS_CODE_INTERNAL_ERROR', 500);